flags: {}
resolver: lts-18.28
extra-package-dbs: []

  #nix:
  #   enable: true
  #  packages:
  #   - libcxx
  #   - icu

packages:
- ./rasa
- ./rasa-ext-cmd
- ./rasa-ext-cursors
- ./rasa-ext-files
- ./rasa-ext-logger
- ./rasa-ext-slate
- ./rasa-ext-views
- ./rasa-ext-vim
- ./rasa-example-config
- ./text-lens
- ./eve


# Uncomment the following if you'd like to use a locally installed version
# of icu4c INSTEAD of relying on nix.
#extra-lib-dirs:
#- /usr/local/opt/icu4c/lib
#extra-include-dirs:
#- /usr/local/opt/icu4c/include

pvp-bounds: both
